services:
  authentik-ldap:
    image: ghcr.io/goauthentik/ldap:${AUTHENTIK_TAG:-2026.5.6}
    container_name: authentik-ldap
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3890:3389" # LDAP
      - "6360:6636" # LDAPS
    environment:
      AUTHENTIK_HOST: "http://server:9000"
      AUTHENTIK_INSECURE: "true"
      AUTHENTIK_TOKEN: "YOUR_AUTHENTIK_OUTPOST_TOKEN"
networks:
  default:
    name: authentik_default
    external: true
